sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t tormenteddan/docker-react .
script:
  - docker run -e CI=true tormenteddan/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-863153807495"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"