version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: tormenteddan/frontend:dev
    ports:
      - "3000:3000"
    volumes:
      - frontend-dependencies:/app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: tormenteddan/frontend:test
    volumes:
      - frontend-dependencies:/app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
volumes:
  frontend-dependencies:
